feat: modernize RatingSampleControl
AvaloniaUI/Avalonia.Samples pull request #66
Opened 2023-11-16 11:13 UTC by workgroupengineering

## What does the pull request do?

**Scope of this PR:**
- [x] fix or update to an existing sample
- [ ] add a new sample

## What is the current behavior?

## Checklist

**If this is a new Sample**
- [ ] Added a ReadMe-file
- [ ] Updated the landing page
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with a link to your sample in the related documentation page

**In any case**
- [ ] Spell-checking done
- [ ] Checked if all hyperlinks work
- [ ] Checked if all images are visible

## Fixed issues

2023-11-16 12:03 UTC, timunie requested changes
Thx for taking this up 🙏  

I'd like to some more explanations about Styles vs ControlThemes. I think this is quite confusing if no link to the docs is present.

2023-11-16 12:03 UTC, timunie commented on src/Avalonia.Samples/CustomControls/RatingControlSample/README.adoc
> +While we can already add a `RatingControl` to our View, we will see nothing as there is no `RatingControl` available. To change this we add another folder called `Styles`. Add a file called `RatingSt
the folder should be Themes instead of Styles in this case. 

I'd like to see at least a hint that styles also work, but in 11.0 ControlThemes are preferred. We may want to link to docs about them if exists.

2023-11-16 13:38 UTC, workgroupengineering commented
> Thx for taking this up 🙏
> 
> I'd like to some more explanations about Styles vs ControlThemes. I think this is quite confusing if no link to the docs is present.

I think the information regarding when to use the `ControlTheme` vs  `Styles` should be relegated to the documentation, the examples should only show best practices.

2023-11-16 13:58 UTC, timunie commented
> I think the information regarding when to use the ControlTheme vs Styles should be relegated to the documentation, the examples should only show best practices.

Yeah exactly. In the sample, we just add a link to the docs in that case. Sorry if it was a misunderstanding here. I wanted to have a link to: https://docs.avaloniaui.net/docs/next/basics/user-interface/styling/control-themes

2023-11-19 10:04 UTC, timunie commented
@workgroupengineering im trying it soon.

2023-11-24 10:13 UTC, timunie commented
Looks good to me besides one typo. I'll merge it now as is and add a fix for the typo directly after. 

Thank you 🙏

2023-11-24 10:13 UTC, merged